export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_PRODUCT_FOR_PAGE = 'FETCH_PRODUCT_FOR_PAGE';
export const GET_BLOG_DETAILS = 'GET_BLOG_DETAILS';
export const GET_BLOG_COMMENT_DETAILS = 'GET_BLOG_COMMENT_DETAILS'